### ISSUE TITLE
滑动切换页面跳页面会报错

### ISSUE THREAD

**Issue by ichynul** [Frank-Zhu/PullZoomView#11]
ViewPager +fragmentsList +底部控制按钮做的切换页面。顺序点击控制的时候没问题，但跳着点就会报错。PullToZoomScrollView 页面是第三页，1跳到3，1跳到4或4跳到2时都会报错。
后来在网上找到解决方法 mViewPager.setOffscreenPageLimit(4);//初始化时全部预加载
不知道是bug还是使用方法的问题。发上来希望能帮助遇到同样问题的朋友
Thread [<1> main] (Suspended (exception IllegalArgumentException))	
	<VM does not provide monitor information>	
	PullToZoomScrollViewEx(View).onRestoreInstanceState(Parcelable) line: 12993	
	PullToZoomScrollViewEx(PullToZoomBase).onRestoreInstanceState(Parcelable) line: 60	
	PullToZoomScrollViewEx(View).dispatchRestoreInstanceState(SparseArray) line: 12969	
	PullToZoomScrollViewEx(ViewGroup).dispatchRestoreInstanceState(SparseArray) line: 2761	
	LinearLayout(ViewGroup).dispatchRestoreInstanceState(SparseArray) line: 2767	
	LinearLayout(View).restoreHierarchyState(SparseArray) line: 12947	
	UserFragment(Fragment).restoreViewState(Bundle) line: 447	
	FragmentManagerImpl.moveToState(Fragment, int, int, int, boolean) line: 960	
	FragmentManagerImpl.attachFragment(Fragment, int, int) line: 1291	
	BackStackRecord.run() line: 672	
	FragmentManagerImpl.execPendingActions() line: 1478	
	FragmentManagerImpl.executePendingTransactions() line: 478	
	RightPagerAdapter(FragmentPagerAdapter).finishUpdate(ViewGroup) line: 141	
	MianViewPager(ViewPager).populate(int) line: 1068	
	MianViewPager(ViewPager).setCurrentItemInternal(int, boolean, boolean, int) line: 550	
	MianViewPager(ViewPager).setCurrentItemInternal(int, boolean, boolean) line: 509	
	MianViewPager(ViewPager).setCurrentItem(int) line: 490	
	MainActivity$MyOnTabsClickListener.onClick(View) line: 182

**Comment by Frank-Zhu** [comment]
check [issues 10](https://github.com/Frank-Zhu/PullZoomView/issues/10)

**Comment by Frank-Zhu** [comment]
fix and Updated with the latest code
