### ISSUE TITLE
Thanks,I have looked for this effect very long time.

### ISSUE THREAD

**Issue by Vurtex** [Frank-Zhu/PullZoomView#13]

**Comment by Frank-Zhu** [comment]
@Vurtex What is the problem?

**Comment by liushuhua** [comment]
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

**Comment by Frank-Zhu** [comment]
@liushuhua update your SDK

**Comment by liushuhua** [comment]
3q
