### ISSUE TITLE
ScrollView Bounce not working

### ISSUE THREAD

**Issue by faizandedia** [Frank-Zhu/PullZoomView#14]
I am trying to use PullToZoomScrollViewEx , it is working fine when the height of content view is less then the height of screen, means if content goes out of the screen, zooming stops working. I am using note 3 device. can you please check what is the issue? I tried to use the demo code as well having same issue.

**Comment by faizandedia** [comment]
any update?

**Comment by Frank-Zhu** [comment]
@faizandedia sorry, I tried to use the demo code is working.(Nexus 5 and S4)

[PullToZoomScrollActivity](https://github.com/Frank-Zhu/PullZoomView/blob/master/PullToZoomView/app/src/main/java/com/ecloud/pulltozoomview/demo/PullToZoomScrollActivity.java)

```java
DisplayMetrics localDisplayMetrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(localDisplayMetrics);
        int mScreenHeight = localDisplayMetrics.heightPixels;
        int mScreenWidth = localDisplayMetrics.widthPixels;
        LinearLayout.LayoutParams localObject = new LinearLayout.LayoutParams(mScreenWidth, mScreenHeight + 20);//This Screen Height
        scrollView.setHeaderLayoutParams(localObject);
```

**Comment by Frank-Zhu** [comment]
@faizandedia It`s work?

**Comment by faizandedia** [comment]
I disabled the feature from that screen.

**Comment by Frank-Zhu** [comment]
@faizandedia ok, Close this issues
