### ISSUE TITLE
AppCompatActivity and using ToolBar with transparent status bar

### ISSUE THREAD

**Issue by rogue5** [Frank-Zhu/PullZoomView#22]
When I switch PullToZoomScrollActivity to AppCompatActivity and use Toolbar in the layout with transparent status bar, the image doesn't always start at the top of the status bar.

Also, when you get the layoutParams to make it work, at this line.
        LinearLayout.LayoutParams localObject = new LinearLayout.LayoutParams(mScreenWidth, (int) (7.0F \* (mScreenWidth / 16.0F)));

Then the Pull down to Zoom still doesn't start until the bottom of the status bar and the status bar has a light grey background.

![screenshot_2015-07-22-23-05-01](https://cloud.githubusercontent.com/assets/4544126/8842496/e0cdefd6-30c8-11e5-80f0-22f998b3f76f.png)

Any ideas on the pull down to zoom from the top of the status bar?

In the mean time, I put     android:background="?attr/colorPrimaryDark"  in the profile_zoom_view.xml ImageView so the grey status bar will be gone.

**Comment by Frank-Zhu** [comment]
@rogue5  any your code?
This is my layout ,It's can work

``` xml
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.ecloud.pulltozoomview.PullToZoomScrollViewEx
        android:id="@+id/scroll_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <android.support.v7.widget.Toolbar
        android:id="@+id/tool_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"/>
</FrameLayout>
```
