### ISSUE TITLE
contenview里有viewpager时，mRootView的测量高度大于mRootContainer的测量高度

### ISSUE THREAD

**Issue by ray007great** [Frank-Zhu/PullZoomView#26]
测量高度我指getMeasuredHeight。
已经在源代码里将mRootContainer的layoutparms宽高设置为了match_parent
导致的结果就是contentView里match_parent的组件并没有占据剩下的整个屏幕（我碰到的组件是viewpager没有显示）。

**Comment by ray007great** [comment]
找到原因了 = 。=
是因为createRootView里create的是一个scrollview
scrollview内的组件match_parent会有些问题
做些小修改就可以了= 。=

**Comment by Christain** [comment]
@ray007great 你好，我也遇到contentview里面要用viewpager。我现在viewpager不显示，请问下你是怎么解决的呢，谢谢

**Comment by amanzan** [comment]
I tried to add a ViewPager to contentView and it is not showing, did you guys manage to do this?
