### ISSUE TITLE
how to get scrollY

### ISSUE THREAD

**Issue by rd-wang** [Frank-Zhu/PullZoomView#28]
How to monitor headView slid off the screen  .I tried using add ScrollListener and override onTouchEvent ,but it does not work.

**Comment by Frank-Zhu** [comment]
@wrd1110 no interface,you can add listener
https://github.com/Frank-Zhu/PullZoomView/blob/master/PullToZoomView/library/src/main/java/com/ecloud/pulltozoomview/PullToZoomScrollViewEx.java#L50

**Comment by rd-wang** [comment]
I ignored the decision condition.can not get ScrollY() ,now it's OK.
