### ISSUE TITLE
zoomView无法正常呈现，被contentView遮挡

### ISSUE THREAD

**Issue by susuzero** [Frank-Zhu/PullZoomView#34]
很感谢提供这么酷的控件，但在使用中遇到一些问题
英文比较烂，描述就直接写中文了
我在Activity中仅有此控件：PullToZoomScrollViewEx
但是呈现结果却不尽人意，zoomView被遮挡，且图片高度较高的情况下无法正常缩放
![2015-11-02 17 16 35](https://cloud.githubusercontent.com/assets/2647639/10877931/82093f56-8185-11e5-8bb9-a8b19e6b2b58.png)

代码如下如下
MainActivity
![2015-11-02 17 30 52](https://cloud.githubusercontent.com/assets/2647639/10878328/d7ef882e-8187-11e5-9923-62ed229d2dd1.png)

activity_main.xml
![2015-11-02 17 31 06](https://cloud.githubusercontent.com/assets/2647639/10878349/f96eeed6-8187-11e5-8a89-ac4f96159773.png)

contentView
![2015-11-02 17 32 07](https://cloud.githubusercontent.com/assets/2647639/10878362/0c206dfc-8188-11e5-8c58-994d5e6fca2b.png)

zoomView
![2015-11-02 17 32 36](https://cloud.githubusercontent.com/assets/2647639/10878374/14a42c02-8188-11e5-9ab3-b6732a93596e.png)

headerView
![2015-11-02 17 32 25](https://cloud.githubusercontent.com/assets/2647639/10878386/1fc9bf84-8188-11e5-99a9-73704cbc7de4.png)

顺便说一句，Gradle添加有问题，Manifest提示错误

**Comment by susuzero** [comment]
问题解决，在contentView中加入android：background属性即可，至于为什么会这样就不知道了。
Gradle中添加依赖依然有问题
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:15:9-43
>     is also present at [com.github.frank-zhu:pullzoomview:1.0.0] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher)
>     Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:12:5-122:19 to override

**Comment by Frank-Zhu** [comment]
@susuzero 好的，我处理一下gradle依赖，感谢反馈！

**Comment by commonslok** [comment]
Error:Execution failed for task ':app:processDebugManifest'.

Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:15:9-43
is also present at [com.github.frank-zhu:pullzoomview:1.0.0] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher)
Suggestion: add 'tools:replace="android:icon"' to element at AndroidManifest.xml:12:5-122:19 to override

这个问题as已经给出建议了，在manifest.xml里加tools:replace="android:icon
