### ISSUE TITLE
PullToZoomScrollViewEx 对 2.3的兼容

### ISSUE THREAD

**Issue by 3349516** [Frank-Zhu/PullZoomView#4]
PullToZoomScrollViewEx 滑动的时候..无法显示Zoomview.

**Comment by tanranran** [comment]
PullToZoomScrollViewEx 如何监听滑动到底部呢?

**Comment by renshu16** [comment]
华为Y325-T00 Android版本2.3.6;
PullToZoomScrollViewEx 无法显示headView和zoomView; headView的点击事件可以响应，ScrollView可以下拉，只是headView和zoomView不显示。
跟楼上反馈2.3bug的情况应该是一样的，麻烦Frank-Zhu看看，针对2.3系统如何兼容
