### ISSUE TITLE
PullToZoomListViewEx.onRestoreInstanceState(PullToZoomListViewEx.java:332)

### ISSUE THREAD

**Issue by jzhu1224** [Frank-Zhu/PullZoomView#7]
12-10 17:29:07.293: W/System.err(10310): java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.AbsListView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/pullToZoomListView. Make sure other views do not use the same id.

**Comment by Frank-Zhu** [comment]
check [issues 10](https://github.com/Frank-Zhu/PullZoomView/issues/10)
