### ISSUE TITLE
PullToZoomScrollView 不能滑动

### ISSUE THREAD

**Issue by linger1216** [Frank-Zhu/PullZoomView#9]
在content中所有可见区域添加OnClickListener, 则scrollvview zoom 效果失效。

可能是事件传递方面略有bug。

please check。

**Comment by Frank-Zhu** [comment]
@linger1216 你是用的PullToZoomScrollViewEx还是那个文件？我用PullToZoomScrollViewEx测试了我的DEMO，特意在test1的地方下来，没有发现有这个BUG

**Comment by hmg25** [comment]
是PullToZoomScrollView这个类，不是PullToZoomScrollViewEx这个类

**Comment by Frank-Zhu** [comment]
@hmg25 PullToZoomScrollView这个类已弃用，你用PullToZoomScrollViewEx类即可
